name: React build
on: 
  push: # main Branch에서 push 이벤트가 일어났을 때만 실행
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repository.fork == false  # Fork된 레포지토리에서 실행되지 않도록 설정
    steps:
      - name: Checkout source code. # 레포지토리 체크아웃
        uses: actions/checkout@main

      - name: Cache node modules # node modules 캐싱
        uses: actions/cache@v1
        with:
          path: node_modules # 프로젝트의 node_modules가 있는 경로로 설정
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies # 의존 파일 설치
        run: npm install # npm install을 실행할 경로로 설정

      - name: Create .env file # 환경 변수 파일 생성
        run: |
          echo "VITE_KAKAO_ADMIN_API=${{ secrets.VITE_KAKAO_ADMIN_API }}" >> .env
          echo "VITE_KAKAO_JS_API=${{ secrets.VITE_KAKAO_JS_API }}" >> .env
          echo "VITE_KAKAO_REST_API=${{ secrets.VITE_KAKAO_REST_API }}" >> .env
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env
          echo "VITE_SITE_URL=${{ secrets.VITE_SITE_URL }}" >> .env
          echo "VITE_WS_BROKER_URL=${{ secrets.VITE_WS_BROKER_URL }}" >> .env

      - name: Build # React Build
        run: npm run build # npm run build를 실행할 경로로 설정

      - name: Deploy # S3에 배포하기
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            dist s3://daitgym
        
      - name: Invalidate CloudFront # CloudFront 캐시 무효화
        uses: chetan/invalidate-cloudfront-action@master
        env:
          PATHS: '/*' 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          AWS_REGION: ' us-east-1' 
          DISTRIBUTION: ${{ secrets.AWS_DISTRIBUTION_ID }} 
